
import React from 'react';
import { Message } from '../types';
import { YakshxIcon } from './icons/YakshxIcon';
import { UserIcon } from './icons/UserIcon';

interface MessageBubbleProps {
  message: Message;
}

const LoadingBubble: React.FC<{content?: string}> = ({ content }) => (
    <div className="flex items-center gap-4">
        <div className="flex items-center space-x-2">
            <div className="w-3 h-3 bg-light-text-secondary dark:bg-dark-text-secondary rounded-full animate-pulse [animation-delay:-0.3s]"></div>
            <div className="w-3 h-3 bg-light-text-secondary dark:bg-dark-text-secondary rounded-full animate-pulse [animation-delay:-0.15s]"></div>
            <div className="w-3 h-3 bg-light-text-secondary dark:bg-dark-text-secondary rounded-full animate-pulse"></div>
        </div>
        {content && <p className="text-sm text-light-text-secondary dark:text-dark-text-secondary">{content}</p>}
    </div>
)

const MessageBubble: React.FC<MessageBubbleProps> = ({ message }) => {
  const isUser = message.role === 'user';

  const renderContent = () => {
    switch (message.type) {
      case 'text':
        return <p className="whitespace-pre-wrap break-words">{message.content}</p>;
      case 'image':
        return <img src={message.content} alt="Generated by AI" className="rounded-lg max-w-full md:max-w-md" />;
      case 'loading':
        return <LoadingBubble content={message.content} />;
      case 'error':
        return <p className="text-red-500">{message.content}</p>;
      default:
        return null;
    }
  };

  return (
    <div className={`flex items-start gap-4 animate-fadeIn ${isUser ? 'justify-end' : ''}`}>
      {!isUser && (
        <div className="flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center bg-light-accent dark:bg-dark-accent text-white">
          <YakshxIcon className="w-5 h-5" />
        </div>
      )}
      <div className={`max-w-2xl px-5 py-3 rounded-2xl ${isUser ? 'bg-light-accent dark:bg-dark-accent text-white rounded-br-none' : 'bg-light-card dark:bg-dark-card rounded-bl-none'}`}>
        {renderContent()}
      </div>
      {isUser && (
        <div className="flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center bg-gray-200 dark:bg-gray-700">
          <UserIcon className="w-5 h-5" />
        </div>
      )}
    </div>
  );
};

export default React.memo(MessageBubble);